### ISSUE TITLE
Add option to connect to custom port of local server

### ISSUE THREAD

**Issue by gabrielcossette** [jaumeortola/languagetool-msword10-addin#1]
Hi!

It would be great to have an option to connect to a custom port of the local server (other than 8081), in case it is already used by something else (e.g. McAfee antivirus).

At least a way to manually change the setting in a registry value or a configuration file would be appreciated (let us know if there is one already, I didn't find any).

Thanks!

**Comment by jaumeortola** [comment]
Hi, 

I am not able to find the settings file once the program is installed. So I have made a [draft release](https://github.com/jaumeortola/languagetool-msword10-addin/releases) where you can change manually the server field in the settings dialog. Let me know if it works for you.

**Comment by gabrielcossette** [comment]
Sorry for the delay. Just tested and it's working well, thanks a bunch!
