### ISSUE TITLE
Error message upon setup

### ISSUE THREAD

**Issue by harko888** [jaumeortola/languagetool-msword10-addin#9]
Hello,

I am quite a newbie and would like to use this Add-in for Word. I downloaded everything but I always get an error message, saying that the certificate or the save location are not trustworthy. I have Windows 10 with newest updates and Microsoft Office Word 2016. I know that it is not tested on this Version of Word but the setup.exe should start up or not? I have NET Framework 4.7.2. I uploaded a Screenshot of the error, it is in German as my Windows is in German but I hope you can help me.
![unbenannt](https://user-images.githubusercontent.com/40799802/42227105-08e6b098-7ee1-11e8-86a5-ffc33f1a2c22.PNG)

**Comment by jaumeortola** [comment]
Hello, 

The certificate of the last version had expired. Now we have published a new version with an updated certificate. Try it and tell us if it works for you. As you know, Microsoft Office Word 2016 has not been tested. You have a paying alternative [here](https://languagetool.org/#add-on), with a different technology.

**Comment by harko888** [comment]
Thank you very much. The new version is working without problems on Windows Office 2016 :)
